version: '2.4'

services:

  config-server:
    build:
      context: config-server
    image: com/cargo/booking/config-server:0.1
    networks:
      - cargo-booking-network
    ports:
      - "8082:8082"
    restart: always

  discovery-server:
    build:
      context: discovery-server
    depends_on:
      - config-server
    image: com/cargo/booking/discovery-server:0.1
    networks:
      - cargo-booking-network
    ports:
      - "8761:8761"
    restart: always

  internal-api-gateway:
    build:
      context: internal-api-gateway
    depends_on:
      - config-server
      - discovery-server
    environment:
      ACTIVE_PROFILES: docker
      CONFIG_SERVER_HOST: config-server
    image: com/cargo/booking/internal-api-gateway:0.1
    networks:
      - cargo-network
    ports:
      - "9001:9001"
    restart: always

  api-gateway:
    build:
      context: api-gateway
    depends_on:
      - config-server
      - discovery-server
    environment:
      ACTIVE_PROFILES: docker
      CONFIG_SERVER_HOST: config-server
    image: com/cargo/booking/api-gateway:0.1
    networks:
      - cargo-network
    ports:
      - "8081:8081"
    restart: always
    
  nsi-service:
    build:
      context: nsi-service
    depends_on:
      - config-server
      - db
      - discovery-server
    environment:
      ACTIVE_PROFILES: docker
      CONFIG_SERVER_HOST: config-server
    image: com/cargo/booking/nsi-service:0.1
    networks:
      - cargo-network
    restart: always

  db:
    build:
      context: database
    image: com/cargo/booking/pg-sql-server:0.1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      PG_DATABASE: cargo
      PG_USER: cargo
      PG_PASSWORD: 'postgres'
      PG_TIMEZONE: 'Asia/Yekaterinburg'
    networks:
      - cargo-booking-network
    restart: always

networks:
  cargo-booking-network:
    driver: bridge

volumes:
  db_data:

