server:
  port: ${SERVER_PORT:8083}
  shutdown: graceful

spring:
  application:
    name: nsi-service
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8082
  profiles:
    active: ${ACTIVE_PROFILES:}