server:
  port: ${SERVER_PORT:9002}

spring:
  application:
    name: claim-service
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8082
  profiles:
    active: ${ACTIVE_PROFILES:}
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

