server:
  port: 8082

spring:
  application:
    name: config-server
  profiles:
    active: ${ACTIVE_PROFILES:native}
  cloud:
    config:
      server:
        vault:
          kv-version: 2
          authentication: TOKEN
          token: ${VAULT_TOKEN:}
